### ISSUE TITLE
sass source files in the wrong directory

### ISSUE THREAD

**Issue by gmagnenat** [Cinquantesix/00-frontendMentorBoilerplate#3]
sass files should be placed in a sass directory to follow what's in the build script

-> main.scss

`src/sass/main.scss`

**Comment by Cinquantesix** [comment]
Can't read the path you talk about. Wich part of the script do this? I don't find my "main.scss" in the script…

**Comment by gmagnenat** [comment]
Seems like you fixed that one ;)

**Comment by Cinquantesix** [comment]
Yeah, I do the suggest, but I don't really understand where I can see the path…
